# Generated by Django 2.0.6 on 2018-06-07 11:16

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180607_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(default=0, verbose_name='内容'),
        ),
    ]
