# Generated by Django 2.0.6 on 2018-06-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_aperation', '0002_auto_20180607_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userleavingmessage',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
    ]
